### PR TITLE
adapt to Cassandra 2.1

### PR DESCRIPTION
**Pull request by tschottdorf**
- added rpc_{max,min}_threads, as 2.0+ with rpc_type=hsha will try to spin
  up MAX_INT processes unless rpc_max_threads is set.
- versioned config and env script handling to map versions A.B.C to A.B
  instead of the previous A (necessitated by incompatibilities between
  2.0 and 2.1)
- new config file for 2.1 (multithreaded_compaction was removed and new
  options added, otherwise no intentional changes)
- changed the default of start_native_transport to 'true' since in 2.1,
  cqlsh uses native transport and it looks like a sensible default.
- changed default version to 2.1.2, the latest stable version at time of
  writing.

The specs pass and the changes *should* be backwards compatible.

Change-Id: Iaf770c951f980e62a0a19c381b601a817fda9cf4

### CODE REVIEW

**Comment by AlexRRR** [comment]
@tschottdorf thanks for pull request! @msimonin any news on merging this? It is sorely needed around here. It seems that the build failed on puppet 2.7.0 tests, but that release has already reached EOL.

**Comment by msimonin** [comment]
Hi, thanks for the work @tschottdorf.
Can you squash your commits  and make the PR on develop  ? 
I'll remove the support for puppet 2.7.0

**Comment by tschottdorf** [comment]
Yep, will do over the weekend.

**Comment by tschottdorf** [comment]
now in #11

**Pull request closed without merging**
